/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJDialog.java
 *
 * Created on 05-Dec-2009, 20:37:03
 */

package net.nikr.eve.jeveasset.gui.dialogs;

/**
 *
 * @author Andrew
 */
public class NewJDialog extends javax.swing.JDialog {

    /** Creates new form NewJDialog */
    public NewJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
		// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
		private void initComponents() {
			
			algorithm = new javax.swing.JComboBox();
			descriptionSP = new javax.swing.JScrollPane();
			descriSP = new javax.swing.JTextArea();
			availableSP = new javax.swing.JScrollPane();
			availSP = new javax.swing.JList();
			add = new javax.swing.JButton();
			remove = new javax.swing.JButton();
			waypointsSP = new javax.swing.JScrollPane();
			waypoSP = new javax.swing.JList();
			addRandom = new javax.swing.JButton();
			waypointsRemaining = new javax.swing.JLabel();
			calculate = new javax.swing.JButton();
			progress = new javax.swing.JLabel();
			availableRemaining = new javax.swing.JLabel();
			cancel = new javax.swing.JButton();
			
			setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
			
			algorithm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
			
			descriSP.setColumns(20);
			descriSP.setRows(5);
			descriptionSP.setViewportView(descriSP);
			
			availSP.setModel(new javax.swing.AbstractListModel() {
				String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
				public int getSize() { return strings.length; }
				public Object getElementAt(int i) { return strings[i]; }
			});
			availableSP.setViewportView(availSP);
			
			add.setText("jButton1");
			
			remove.setText("jButton2");
			
			waypoSP.setModel(new javax.swing.AbstractListModel() {
				String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
				public int getSize() { return strings.length; }
				public Object getElementAt(int i) { return strings[i]; }
			});
			waypointsSP.setViewportView(waypoSP);
			
			addRandom.setText("jButton3");
			
			waypointsRemaining.setText("jLabel1");
			
			calculate.setText("jButton4");
			
			progress.setText("jLabel2");
			
			availableRemaining.setText("avail");
			
			cancel.setText("jButton1");
			
			javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
			getContentPane().setLayout(layout);
			layout.setHorizontalGroup(
					layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(layout.createSequentialGroup()
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
					.addComponent(availableRemaining, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(availableSP, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addComponent(remove)
					.addComponent(add)
					.addComponent(addRandom))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addComponent(calculate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
					.addComponent(waypointsRemaining, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
					.addComponent(waypointsSP, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
					.addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
					.addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
					.addComponent(algorithm, javax.swing.GroupLayout.Alignment.TRAILING, 0, 380, Short.MAX_VALUE)
					.addComponent(descriptionSP, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
					.addContainerGap())
					);
			layout.setVerticalGroup(
					layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(layout.createSequentialGroup()
					.addGap(4, 4, 4)
					.addComponent(progress)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(algorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(descriptionSP, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
					.addComponent(waypointsSP, 0, 0, Short.MAX_VALUE)
					.addComponent(availableSP, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
					.addGroup(layout.createSequentialGroup()
					.addComponent(add)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(remove)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(addRandom)))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
					.addComponent(waypointsRemaining)
					.addComponent(availableRemaining))
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(calculate)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(cancel)
					.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
					);
			
			pack();
		}// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog dialog = new NewJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

		// Variables declaration - do not modify//GEN-BEGIN:variables
		private javax.swing.JButton add;
		private javax.swing.JButton addRandom;
		private javax.swing.JComboBox algorithm;
		private javax.swing.JList availSP;
		private javax.swing.JLabel availableRemaining;
		private javax.swing.JScrollPane availableSP;
		private javax.swing.JButton calculate;
		private javax.swing.JButton cancel;
		private javax.swing.JTextArea descriSP;
		private javax.swing.JScrollPane descriptionSP;
		private javax.swing.JLabel progress;
		private javax.swing.JButton remove;
		private javax.swing.JList waypoSP;
		private javax.swing.JLabel waypointsRemaining;
		private javax.swing.JScrollPane waypointsSP;
		// End of variables declaration//GEN-END:variables

}
